[package]
name = "system76-support"
version = "0.1.0"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exit-status-ext = { git = "https://github.com/pop-os/exit-status-ext" }
gtk = "0.7.0"
gio = "0.7.0"
glib = "0.8.2"
cascade = "0.1.3"
futures = "0.3.1"
tokio = { version = "0.2.0-alpha.6", features = ["process"]}
anyhow = "1.0.22"
libc = "0.2.65"
tempfile = "3.1.0"
async-std = "1.1.0"
